export enum ErrorCode {
  DISABLED_USER = 'DISABLED_USER',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_TOKEN = 'INVALID_TOKEN',
  UNACTIVATED_USER = 'UNACTIVATED_USER',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
}
